//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Hospital.HelperClasses
{
	/// <summary>Field Creation Class for entity DoctorEntity</summary>
	public partial class DoctorFields
	{
		/// <summary>Creates a new DoctorEntity.Address field instance</summary>
		public static EntityField2 Address { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DoctorFieldIndex.Address); }}
		/// <summary>Creates a new DoctorEntity.Email field instance</summary>
		public static EntityField2 Email { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DoctorFieldIndex.Email); }}
		/// <summary>Creates a new DoctorEntity.FirstName field instance</summary>
		public static EntityField2 FirstName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DoctorFieldIndex.FirstName); }}
		/// <summary>Creates a new DoctorEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DoctorFieldIndex.Id); }}
		/// <summary>Creates a new DoctorEntity.LastName field instance</summary>
		public static EntityField2 LastName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DoctorFieldIndex.LastName); }}
	}

	/// <summary>Field Creation Class for entity PatientEntity</summary>
	public partial class PatientFields
	{
		/// <summary>Creates a new PatientEntity.Address field instance</summary>
		public static EntityField2 Address { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PatientFieldIndex.Address); }}
		/// <summary>Creates a new PatientEntity.AssignedDoctorId field instance</summary>
		public static EntityField2 AssignedDoctorId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PatientFieldIndex.AssignedDoctorId); }}
		/// <summary>Creates a new PatientEntity.Email field instance</summary>
		public static EntityField2 Email { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PatientFieldIndex.Email); }}
		/// <summary>Creates a new PatientEntity.FirstName field instance</summary>
		public static EntityField2 FirstName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PatientFieldIndex.FirstName); }}
		/// <summary>Creates a new PatientEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PatientFieldIndex.Id); }}
		/// <summary>Creates a new PatientEntity.LastName field instance</summary>
		public static EntityField2 LastName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PatientFieldIndex.LastName); }}
	}
	

}