//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Hospital.HelperClasses;
using Hospital.FactoryClasses;
using Hospital.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Hospital.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Doctor'.<br/><br/></summary>
	[Serializable]
	public partial class DoctorEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<PatientEntity> _patients;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static DoctorEntityStaticMetaData _staticMetaData = new DoctorEntityStaticMetaData();
		private static DoctorRelations _relationsFactory = new DoctorRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Patients</summary>
			public static readonly string Patients = "Patients";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class DoctorEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public DoctorEntityStaticMetaData()
			{
				SetEntityCoreInfo("DoctorEntity", InheritanceHierarchyType.None, false, (int)Hospital.EntityType.DoctorEntity, typeof(DoctorEntity), typeof(DoctorEntityFactory), false);
				AddNavigatorMetaData<DoctorEntity, EntityCollection<PatientEntity>>("Patients", a => a._patients, (a, b) => a._patients = b, a => a.Patients, () => new DoctorRelations().PatientEntityUsingAssignedDoctorId, typeof(PatientEntity), (int)Hospital.EntityType.PatientEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static DoctorEntity()
		{
		}

		/// <summary> CTor</summary>
		public DoctorEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public DoctorEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this DoctorEntity</param>
		public DoctorEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Doctor which data should be fetched into this Doctor object</param>
		public DoctorEntity(System.Int64 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Doctor which data should be fetched into this Doctor object</param>
		/// <param name="validator">The custom validator object for this DoctorEntity</param>
		public DoctorEntity(System.Int64 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected DoctorEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Patient' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoPatients() { return CreateRelationInfoForNavigator("Patients"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this DoctorEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static DoctorRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Patient' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathPatients { get { return _staticMetaData.GetPrefetchPathElement("Patients", CommonEntityBase.CreateEntityCollection<PatientEntity>()); } }

		/// <summary>The Address property of the Entity Doctor<br/><br/></summary>
		/// <remarks>Mapped on  table field: "doctor"."address".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Address
		{
			get { return (System.String)GetValue((int)DoctorFieldIndex.Address, true); }
			set	{ SetValue((int)DoctorFieldIndex.Address, value); }
		}

		/// <summary>The Email property of the Entity Doctor<br/><br/></summary>
		/// <remarks>Mapped on  table field: "doctor"."email".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Email
		{
			get { return (System.String)GetValue((int)DoctorFieldIndex.Email, true); }
			set	{ SetValue((int)DoctorFieldIndex.Email, value); }
		}

		/// <summary>The FirstName property of the Entity Doctor<br/><br/></summary>
		/// <remarks>Mapped on  table field: "doctor"."first_name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String FirstName
		{
			get { return (System.String)GetValue((int)DoctorFieldIndex.FirstName, true); }
			set	{ SetValue((int)DoctorFieldIndex.FirstName, value); }
		}

		/// <summary>The Id property of the Entity Doctor<br/><br/></summary>
		/// <remarks>Mapped on  table field: "doctor"."id".<br/>Table field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int64 Id
		{
			get { return (System.Int64)GetValue((int)DoctorFieldIndex.Id, true); }
			set { SetValue((int)DoctorFieldIndex.Id, value); }		}

		/// <summary>The LastName property of the Entity Doctor<br/><br/></summary>
		/// <remarks>Mapped on  table field: "doctor"."last_name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String LastName
		{
			get { return (System.String)GetValue((int)DoctorFieldIndex.LastName, true); }
			set	{ SetValue((int)DoctorFieldIndex.LastName, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'PatientEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(PatientEntity))]
		public virtual EntityCollection<PatientEntity> Patients { get { return GetOrCreateEntityCollection<PatientEntity, PatientEntityFactory>("Doctor", true, false, ref _patients); } }
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace Hospital
{
	public enum DoctorFieldIndex
	{
		///<summary>Address. </summary>
		Address,
		///<summary>Email. </summary>
		Email,
		///<summary>FirstName. </summary>
		FirstName,
		///<summary>Id. </summary>
		Id,
		///<summary>LastName. </summary>
		LastName,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Hospital.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Doctor. </summary>
	public partial class DoctorRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between DoctorEntity and PatientEntity over the 1:n relation they have, using the relation between the fields: Doctor.Id - Patient.AssignedDoctorId</summary>
		public virtual IEntityRelation PatientEntityUsingAssignedDoctorId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Patients", true, new[] { DoctorFields.Id, PatientFields.AssignedDoctorId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticDoctorRelations
	{
		internal static readonly IEntityRelation PatientEntityUsingAssignedDoctorIdStatic = new DoctorRelations().PatientEntityUsingAssignedDoctorId;

		/// <summary>CTor</summary>
		static StaticDoctorRelations() { }
	}
}
